name: CI
on:
  push:
    branches: [main]
jobs:
  ci:
    runs-on: self-hosted
    env:
      GOPRIVATE: git.assilvestrar.club
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Build
        run: make build
      - name: Ko Build & push
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | ko login git.assilvestrar.club -u ${{ secrets.REGISTRY_USER }} --password-stdin
          KO_DOCKER_REPO=git.assilvestrar.club/lourenco/k8s-mtp ko build --bare --platform=linux/amd64 ./cmd/api ./cmd/controller ./cmd/webhook
