{{- if .Values.dex.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: dex-config
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  config.yaml: {{ .Values.dex.config | toYaml | b64enc | quote }}
{{- end}}
